max_width = 120
newline_style = "Unix"
style_edition = "2024"
use_field_init_shorthand = true

# Unstable features below
unstable_features = true
# code can be 100 characters, why not comments?
comment_width = 120
# force contributors to follow the formatting requirement
error_on_line_overflow = true
error_on_unformatted = false
# next 4: why not?
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
format_strings = true
# better grepping
imports_granularity = "Module"
# quicker manual lookup
group_imports = "StdExternalCrate"
# why use an attribute if a normal doc comment would suffice?
normalize_doc_attributes = true
# why not?
wrap_comments = true
